
###
### This file generates automaticly
### Do not change anything at it
### Generated from 'needs.cfg'
###

import re
from BeautifulSoup import BeautifulSoup

tag_check = re.compile(r'^(a|blockquote|p|u|b|i|em|strike|strong|ul|ol|li|sub|sup|br|hr|object|param|embed|h1|h2|h3|h4|h5|h6|center|address|pre|iframe|img|span|table|tr|td|tname|tbody|div|dd|dt)$', re.IGNORECASE)
attr_check = {}
attr_value_check = {}
style_check = {}
style_value_check = {}
attr_check['a'] = re.compile(r'^(name|href|style)$', re.IGNORECASE)
attr_value_check['a'] = {}
attr_value_check['a']['name'] = re.compile(r'^(.*)$', re.IGNORECASE)
attr_value_check['a']['href'] = re.compile(r'^(.*)$', re.IGNORECASE)
attr_value_check['a']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['blockquote'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['blockquote'] = {}
attr_value_check['blockquote']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['p'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['p'] = {}
attr_value_check['p']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['u'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['u'] = {}
attr_value_check['u']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['b'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['b'] = {}
attr_value_check['b']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['i'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['i'] = {}
attr_value_check['i']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['em'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['em'] = {}
attr_value_check['em']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['strike'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['strike'] = {}
attr_value_check['strike']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['strong'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['strong'] = {}
attr_value_check['strong']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['ul'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['ul'] = {}
attr_value_check['ul']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['ol'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['ol'] = {}
attr_value_check['ol']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['li'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['li'] = {}
attr_value_check['li']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['sub'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['sub'] = {}
attr_value_check['sub']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['sup'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['sup'] = {}
attr_value_check['sup']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['br'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['br'] = {}
attr_value_check['br']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['hr'] = re.compile(r'^(class|style)$', re.IGNORECASE)
attr_value_check['hr'] = {}
attr_value_check['hr']['class'] = re.compile(r'^(editor_cut)$', re.IGNORECASE)
attr_value_check['hr']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['object'] = re.compile(r'^(data|width|height|style)$', re.IGNORECASE)
attr_value_check['object'] = {}
attr_value_check['object']['data'] = re.compile(r'^(.*)$', re.IGNORECASE)
attr_value_check['object']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['object']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['object']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['param'] = re.compile(r'^(name|value|style)$', re.IGNORECASE)
attr_value_check['param'] = {}
attr_value_check['param']['name'] = re.compile(r'^(movie|allowFullScreen|allowscriptaccess)$', re.IGNORECASE)
attr_value_check['param']['value'] = re.compile(r'^(http://www\.youtube\.com/.*|true|always)$', re.IGNORECASE)
attr_value_check['param']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['embed'] = re.compile(r'^(src|type|allowfullscreen|width|height|style)$', re.IGNORECASE)
attr_value_check['embed'] = {}
attr_value_check['embed']['src'] = re.compile(r'^((http://www\.youtube\.com/|http://youtube\.com/).*)$', re.IGNORECASE)
attr_value_check['embed']['type'] = re.compile(r'^(application/x-shockwave-falsh)$', re.IGNORECASE)
attr_value_check['embed']['allowfullscreen'] = re.compile(r'^(true|false)$', re.IGNORECASE)
attr_value_check['embed']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['embed']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['embed']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['h1'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['h1'] = {}
attr_value_check['h1']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['h2'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['h2'] = {}
attr_value_check['h2']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['h3'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['h3'] = {}
attr_value_check['h3']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['h4'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['h4'] = {}
attr_value_check['h4']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['h5'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['h5'] = {}
attr_value_check['h5']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['h6'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['h6'] = {}
attr_value_check['h6']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['center'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['center'] = {}
attr_value_check['center']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['address'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['address'] = {}
attr_value_check['address']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['pre'] = re.compile(r'^(style)$', re.IGNORECASE)
attr_value_check['pre'] = {}
attr_value_check['pre']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['iframe'] = re.compile(r'^(src|width|height|frameborder|style)$', re.IGNORECASE)
attr_value_check['iframe'] = {}
attr_value_check['iframe']['src'] = re.compile(r'^((http://player\.vimeo\.com/|http://(vkontakte\.ru|vk\.com)/video_ext\.php|http://www\.youtube\.com/|http://youtube\.com/).*)$', re.IGNORECASE)
attr_value_check['iframe']['width'] = re.compile(r'^([\d]+)$', re.IGNORECASE)
attr_value_check['iframe']['height'] = re.compile(r'^([\d]+)$', re.IGNORECASE)
attr_value_check['iframe']['frameborder'] = re.compile(r'^([\d]+)$', re.IGNORECASE)
attr_value_check['iframe']['style'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['img'] = re.compile(r'^(width|height|style|src|alt)$', re.IGNORECASE)
attr_value_check['img'] = {}
attr_value_check['img']['width'] = re.compile(r'^([\d]+)$', re.IGNORECASE)
attr_value_check['img']['height'] = re.compile(r'^([\d]+)$', re.IGNORECASE)
attr_value_check['img']['style'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_value_check['img']['src'] = re.compile(r'^(.*)$', re.IGNORECASE)
attr_value_check['img']['alt'] = re.compile(r'^(.*)$', re.IGNORECASE)
attr_check['span'] = re.compile(r'^(width|height|align|style)$', re.IGNORECASE)
attr_value_check['span'] = {}
attr_value_check['span']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['span']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['span']['align'] = re.compile(r'^(\w+)$', re.IGNORECASE)
attr_value_check['span']['style'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['table'] = re.compile(r'^(width|height|align|style)$', re.IGNORECASE)
attr_value_check['table'] = {}
attr_value_check['table']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['table']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['table']['align'] = re.compile(r'^(\w+)$', re.IGNORECASE)
attr_value_check['table']['style'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['tr'] = re.compile(r'^(width|height|align|style)$', re.IGNORECASE)
attr_value_check['tr'] = {}
attr_value_check['tr']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['tr']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['tr']['align'] = re.compile(r'^(\w+)$', re.IGNORECASE)
attr_value_check['tr']['style'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['td'] = re.compile(r'^(width|height|align|style)$', re.IGNORECASE)
attr_value_check['td'] = {}
attr_value_check['td']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['td']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['td']['align'] = re.compile(r'^(\w+)$', re.IGNORECASE)
attr_value_check['td']['style'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['tname'] = re.compile(r'^(width|height|align|style)$', re.IGNORECASE)
attr_value_check['tname'] = {}
attr_value_check['tname']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['tname']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['tname']['align'] = re.compile(r'^(\w+)$', re.IGNORECASE)
attr_value_check['tname']['style'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['tbody'] = re.compile(r'^(width|height|align|style)$', re.IGNORECASE)
attr_value_check['tbody'] = {}
attr_value_check['tbody']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['tbody']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['tbody']['align'] = re.compile(r'^(\w+)$', re.IGNORECASE)
attr_value_check['tbody']['style'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['div'] = re.compile(r'^(width|height|align|style)$', re.IGNORECASE)
attr_value_check['div'] = {}
attr_value_check['div']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['div']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['div']['align'] = re.compile(r'^(\w+)$', re.IGNORECASE)
attr_value_check['div']['style'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['dd'] = re.compile(r'^(width|height|align|style)$', re.IGNORECASE)
attr_value_check['dd'] = {}
attr_value_check['dd']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['dd']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['dd']['align'] = re.compile(r'^(\w+)$', re.IGNORECASE)
attr_value_check['dd']['style'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
attr_check['dt'] = re.compile(r'^(width|height|align|style)$', re.IGNORECASE)
attr_value_check['dt'] = {}
attr_value_check['dt']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['dt']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
attr_value_check['dt']['align'] = re.compile(r'^(\w+)$', re.IGNORECASE)
attr_value_check['dt']['style'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
style_check['a'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['a'] = {}
style_value_check['a']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['a']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['a']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['blockquote'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['blockquote'] = {}
style_value_check['blockquote']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['blockquote']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['blockquote']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['p'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['p'] = {}
style_value_check['p']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['p']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['p']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['u'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['u'] = {}
style_value_check['u']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['u']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['u']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['b'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['b'] = {}
style_value_check['b']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['b']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['b']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['i'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['i'] = {}
style_value_check['i']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['i']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['i']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['em'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['em'] = {}
style_value_check['em']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['em']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['em']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['strike'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['strike'] = {}
style_value_check['strike']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['strike']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['strike']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['strong'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['strong'] = {}
style_value_check['strong']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['strong']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['strong']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['ul'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['ul'] = {}
style_value_check['ul']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['ul']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['ul']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['ol'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['ol'] = {}
style_value_check['ol']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['ol']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['ol']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['li'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['li'] = {}
style_value_check['li']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['li']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['li']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['sub'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['sub'] = {}
style_value_check['sub']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['sub']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['sub']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['sup'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['sup'] = {}
style_value_check['sup']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['sup']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['sup']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['br'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['br'] = {}
style_value_check['br']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['br']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['br']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['hr'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['hr'] = {}
style_value_check['hr']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['hr']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['hr']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['object'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['object'] = {}
style_value_check['object']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['object']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['object']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['param'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['param'] = {}
style_value_check['param']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['param']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['param']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['embed'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['embed'] = {}
style_value_check['embed']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['embed']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['embed']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['h1'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['h1'] = {}
style_value_check['h1']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['h1']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['h1']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['h2'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['h2'] = {}
style_value_check['h2']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['h2']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['h2']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['h3'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['h3'] = {}
style_value_check['h3']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['h3']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['h3']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['h4'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['h4'] = {}
style_value_check['h4']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['h4']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['h4']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['h5'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['h5'] = {}
style_value_check['h5']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['h5']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['h5']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['h6'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['h6'] = {}
style_value_check['h6']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['h6']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['h6']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['center'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['center'] = {}
style_value_check['center']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['center']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['center']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['address'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['address'] = {}
style_value_check['address']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['address']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['address']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['pre'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['pre'] = {}
style_value_check['pre']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['pre']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['pre']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['iframe'] = re.compile(r'^(text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['iframe'] = {}
style_value_check['iframe']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['iframe']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['iframe']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['img'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['img'] = {}
style_value_check['img']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['img']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['img']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['img']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['img']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['span'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['span'] = {}
style_value_check['span']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['span']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['span']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['span']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['span']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['table'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['table'] = {}
style_value_check['table']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['table']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['table']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['table']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['table']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['tr'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['tr'] = {}
style_value_check['tr']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['tr']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['tr']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['tr']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['tr']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['td'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['td'] = {}
style_value_check['td']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['td']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['td']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['td']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['td']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['tname'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['tname'] = {}
style_value_check['tname']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['tname']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['tname']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['tname']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['tname']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['tbody'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['tbody'] = {}
style_value_check['tbody']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['tbody']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['tbody']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['tbody']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['tbody']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['div'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['div'] = {}
style_value_check['div']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['div']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['div']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['div']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['div']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['dd'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['dd'] = {}
style_value_check['dd']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['dd']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['dd']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['dd']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['dd']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_check['dt'] = re.compile(r'^(width|height|text-align|margin.*|padding.*)$', re.IGNORECASE)
style_value_check['dt'] = {}
style_value_check['dt']['width'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['dt']['height'] = re.compile(r'^(\d+)$', re.IGNORECASE)
style_value_check['dt']['text-align'] = re.compile(r'^(center|left|right|justify)$', re.IGNORECASE)
style_value_check['dt']['margin.*'] = re.compile(r'^(.*)$', re.IGNORECASE)
style_value_check['dt']['padding.*'] = re.compile(r'^(.*)$', re.IGNORECASE)


def clear_html_code(text):
    soup = BeautifulSoup(text)
    tags = soup.findAll()
    for tag in tags:
        if not tag_check.match(tag.name):
            tag.extract()
        else:
            for attr in tag.attrs[:]:
                if not attr_check[tag.name].match(attr[0]):
                    tag.attrs.remove(attr)
                else:
                    if (attr[0].lower() == "style"):
                        list = attr[1].split(';')
                        res = ""
                        for x in list:
                            if x.find(':') > 0:
                                keys = x.split(':')
                                if style_check[tag.name].match(keys[0]) and (keys[0] not in style_value_check[tag.name] or style_value_check[tag.name][keys[0]].match(keys[1])):
                                    res += x + ';'
                        tag.attrs.remove(attr)
                        tag.attrs.append(("style", res))
                    else:
                        if not attr_value_check[tag.name][attr[0]].match(attr[1]):
                            tag.attrs.remove(attr)
    return unicode(soup)

